# .github/workflows/api-request.yml
name: API Request

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make API request
      run: |
        curl -X PUT "https://api.github.com/repos/NEL227/my-data-repo/contents/data/collected_data.txt" \
        -H "Authorization: token ${{ secrets.API_SECRET_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"message": "Update data", "content": "base64_encoded_content", "sha": "file_sha_if_needed"}'
