# .github/workflows/api-request.yml
name: API Request

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手動でトリガーするオプション

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make API request
      run: |
        curl -X POST "https://api.github.com/repos/NEL227/my-data-repo/contents/data/collected_data.txt" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"message": "Update data", "content": "base64_encoded_content"}'
