name: Update Data

on:
  workflow_dispatch:
    inputs:
      new_data:
        description: 'Data to be added'
        required: true
        type: string

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update data file
        run: |
          echo "${{ github.event.inputs.new_data }}" >> data/collected_data.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data/collected_data.txt
          git commit -m "Update data from GitHub Action"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
