name: Update Data
on:
  workflow_dispatch:
    inputs:
      new_data:
        description: 'The new data to append'
        required: true

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Append new data to file
        run: |
          echo "${{ github.event.inputs.new_data }}" >> data/collected_data.txt
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/collected_data.txt
          git commit -m "Update data via GitHub Actions"
          git push
