name: Update Data

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'New data to append'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Append Data to File
        run: |
          echo "${{ github.event.inputs.data }}" >> data/collected_data.txt

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions Bot'
          author_email: 'actions@example.com'
          message: 'Update collected_data.txt with new data'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
