name: Use API Secret Key

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Data to append to the file'
        required: true
        default: 'No data provided'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Data File
        run: |
          echo "${{ github.event.inputs.data }}" >> data/collected_data.txt
        
      - name: Use API Secret Key
        run: |
          echo "Using API secret key for authentication"
          curl -H "Authorization: Bearer ${{ secrets.API_SECRET_KEY }}" https://api.example.com/resource
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
      
      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions Bot'
          author_email: 'actions@example.com'
          message: 'Update collected_data.txt with new data'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
